# Generated by Django 5.0.2 on 2024-02-17 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(10, message='mobile number must be at least 10 digit numbers .'), django.core.validators.RegexValidator('^9\\d{9}$', message='mobile number must be at least 9 digit and 10 digit long')])),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
